"""Registered outbox event types. Adding an entry here without a registered
subscriber is flagged in CI."""

from __future__ import annotations

# Booking lifecycle
BOOKING_SUBMITTED = "BOOKING_SUBMITTED"
BOOKING_CONFIRMED = "BOOKING_CONFIRMED"
BOOKING_CANCELLED = "BOOKING_CANCELLED"

# Lease lifecycle
LEASE_STARTED = "LEASE_STARTED"
LEASE_MONTHLY_BILLING_DUE = "LEASE_MONTHLY_BILLING_DUE"
LEASE_COMPLETED = "LEASE_COMPLETED"
LEASE_TERMINATED = "LEASE_TERMINATED"

# KYC lifecycle
KYC_DOCUMENT_UPLOADED = "KYC_DOCUMENT_UPLOADED"
KYC_APPROVED = "KYC_APPROVED"
KYC_REJECTED = "KYC_REJECTED"

# Payment lifecycle
PAYMENT_SUCCEEDED = "PAYMENT_SUCCEEDED"
PAYMENT_FAILED = "PAYMENT_FAILED"
PAYMENT_REFUNDED = "PAYMENT_REFUNDED"

# Consent
CONSENT_GRANTED = "CONSENT_GRANTED"
CONSENT_WITHDRAWN = "CONSENT_WITHDRAWN"
